"""The provider-neutral LLM interface of Reasoning V3 (``REV/06``).

Reasoning code (Phases 07+) depends only on this module and ``gateway``: requests, responses, structured-output descriptions and
the error taxonomy. Nothing here knows about OpenRouter, HTTP or any SDK; ``openrouter_client`` and ``fake_provider`` implement
``Transport``.

Every request carries a ``CallContext`` (run, case, work item, request ID, prompt version, source snapshot, evidence fingerprint),
which the gateway records in ``llm_calls`` for every call, successful or not.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Protocol

from atlas_reasoning.frozen import FrozenMap, freeze


@dataclass(frozen=True)
class CallContext:
    """What a call is for. ``request_id`` is generated by the gateway when empty."""

    purpose: str
    request_id: str = ""
    run_id: str | None = None
    case_id: str | None = None
    work_item_id: str | None = None
    prompt_version: str | None = None
    source_snapshot_id: str | None = None
    evidence_fingerprint: str | None = None


@dataclass(frozen=True)
class Message:
    role: str            # "system" | "user" | "assistant"
    content: str

    def __post_init__(self) -> None:
        if self.role not in ("system", "user", "assistant"):
            raise ValueError(f"unknown message role {self.role!r}")


@dataclass(frozen=True)
class StructuredOutput:
    """The JSON shape a response must have. ``schema`` is sent to the provider (self-contained, no external $ref); ``validate``
    returns the problems of a parsed response (empty when it conforms) and is always applied locally, whatever the provider claims."""

    name: str
    schema: FrozenMap
    validate: Callable[[Any], list[str]]
    strict: bool = True


@dataclass(frozen=True)
class ProviderRequest:
    context: CallContext
    messages: tuple[Message, ...]
    output: StructuredOutput | None = None
    max_output_tokens: int | None = None
    reasoning_effort: str | None = None      # provider hint; reasoning text itself is never requested or kept


@dataclass(frozen=True)
class ProviderResponse:
    """A successful completion. ``parsed`` is the validated JSON when the request asked for structured output."""

    request_id: str
    model: str
    content: str
    parsed: Any = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    provider_response_id: str | None = None
    provider_status: str | None = None
    finish_reason: str | None = None
    metadata: FrozenMap = field(default_factory=lambda: freeze({}))


class Transport(Protocol):
    """One attempt at one completion. Raises ``ProviderError`` (never anything provider-specific)."""

    provider_name: str

    def complete(self, request: ProviderRequest, *, model: str, timeout: float) -> ProviderResponse: ...


# --- error taxonomy ---------------------------------------------------------------------------------------------------------


class ProviderError(RuntimeError):
    """A provider call failed. ``error_class`` is stable and stored in ``llm_calls``; messages never contain credentials."""

    error_class = "provider_error"
    retryable = False

    def __init__(self, message: str, *, status: int | None = None, retry_after: float | None = None, provider_status: str | None = None) -> None:
        super().__init__(message)
        self.status, self.retry_after = status, retry_after
        self.provider_status = provider_status or (str(status) if status is not None else None)


class ProviderTimeout(ProviderError):
    error_class, retryable = "timeout", True


class ProviderRateLimited(ProviderError):
    error_class, retryable = "rate_limited", True


class ProviderUnavailable(ProviderError):
    error_class, retryable = "provider_unavailable", True


class ProviderNetworkError(ProviderError):
    error_class, retryable = "network_error", True


class ProviderResponseError(ProviderError):
    """The provider answered with an envelope that is not a valid completion."""

    error_class, retryable = "malformed_response", True


class StructuredOutputError(ProviderError):
    """The completion is not JSON, or not JSON of the requested shape."""

    error_class, retryable = "invalid_structured_output", True


class ProviderAuthError(ProviderError):
    error_class = "authentication"


class ProviderQuotaExceeded(ProviderError):
    error_class = "quota_exceeded"


class ProviderBadRequest(ProviderError):
    error_class = "bad_request"


class ProviderContentFiltered(ProviderError):
    error_class = "content_filtered"


class ProviderTruncated(ProviderError):
    """The completion stopped at the token limit; repeating the same request would stop there again."""

    error_class = "truncated"


class ProviderConfigError(ProviderError):
    error_class = "configuration"


class ProviderInternalError(ProviderError):
    """An unexpected failure inside the transport (a bug), contained like any provider failure."""

    error_class = "internal_error"


ERROR_CLASSES = tuple(cls.error_class for cls in (ProviderError, ProviderTimeout, ProviderRateLimited, ProviderUnavailable, ProviderNetworkError,
                                                  ProviderResponseError, StructuredOutputError, ProviderAuthError, ProviderQuotaExceeded,
                                                  ProviderBadRequest, ProviderContentFiltered, ProviderTruncated, ProviderConfigError,
                                                  ProviderInternalError))


# --- redaction ----------------------------------------------------------------------------------------------------------------

_BEARER = re.compile(r"(?i)(bearer\s+)[A-Za-z0-9._~+/=-]+")
_KEYLIKE = re.compile(r"sk-or-[A-Za-z0-9_-]{8,}")


def redact(text: str, secrets: Sequence[str] = ()) -> str:
    """``text`` with every known secret, bearer token and OpenRouter-style key replaced."""
    for secret in secrets:
        if secret:
            text = text.replace(secret, "***")
    return _KEYLIKE.sub("***", _BEARER.sub(r"\1***", text))


def safe_mapping(values: Mapping[str, Any], secrets: Sequence[str] = ()) -> dict[str, Any]:
    return {key: redact(str(value), secrets) if isinstance(value, str) else value for key, value in values.items()}
